---
- name: Converge
  hosts: all

  vars:
    # controller_fqdn: ""
    # api_key: ""
    # user_email: ""
    # user_password: ""
    #
    # environmentName: ""
    # certificate:
    #   metadata:
    #     name: "www.example.com"
    #     displayName: "Root WWW Cert"
    #     description: "A certificate"
    #   desiredState:
    #     type: "PEM"
    #     privateKey: ""
    #     publicCert: ""

  tasks:
    - include_role:
        name: ansible-role-nginx-controller-certificate
